name: default
banner_height: 260
left_ratio: 0.58
padding:
  x: 48
  y: 24
colors:
  background: "#ECECEC"
  text: "#333333"
  muted: "#5A5A5A"
  divider: "#C8C8C8"
fonts:
  title: 72
  body: 40
  small: 28
divider: true
logo: "BirdStamp / 鸟印"
